<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../FileStorage.Core/FileStorage.Core.csproj" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.104.2" />
    <EmbeddedResource Include="schema.sql" />
  </ItemGroup>
</Project>
